name: Deploy CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server (build on server)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/beta_ci_cd_app/ci_cd
            docker stop beta_ci_cd_app || true
            docker rm beta_ci_cd_app || true
            docker build -t beta_ci_cd_app:latest .
            docker run -d --name beta_ci_cd_app -p 80:3000 beta_ci_cd_app:latest
